all:
	gcc -O2 simple.c -o simple
	gcc -O2 multiplex.c -o multiplex
	gcc -O2 -pthread thread1.c -o thread1
	gcc -O2 -pthread thread2.c -o thread2

clean:
	rm -rf simple
	rm -rf multplex
	rm -rf thread
